plugins {
    id "architectury-plugin" version "3.4-SNAPSHOT" apply false
    id "dev.architectury.loom" version "1.7.435" apply false
    id "com.github.johnrengelman.shadow" version "8.1.1" apply false
}

allprojects {
    apply plugin: "java"
    apply plugin: "maven-publish"

    version = rootProject.mod_version
    group = rootProject.mod_group_id

    repositories {
        maven { url = "https://maven.architectury.dev/" }
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.minecraftforge.net/" }
        maven { url = "https://maven.su5ed.dev/releases" }
        maven {
            name = "Modrinth"
            url = "https://api.modrinth.com/maven"
            content { includeGroup "maven.modrinth" }
        }
        mavenCentral()
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 17
    }
}
